openapi: 3.0.1
info:
  title: Arena API
  description: "<p>REST API'er som er tilbudt av Arena.</p>\n\n<p>Sikkerhet:</p>\n<ul>\n<li>Avhengig av formålet med API'et, støttes aksesstoken utstedt av Azure AD, REST-STS\nog/eller TokenX/ID-porten.</li>\n<li>Preautorisering:</li>\n<ul>\n\t<li>Azure AD: Konsumenter må være registrert med applikasjonsnavn, team og cluster.</li>\n\t<li>REST-STS: Konsumenter må være registrert med servicebruker.</li>\n\t<li>TokenX: Konsumenter må være registrert med applikasjonsnavn, team og cluster.</li>\n</ul>\n<li>Ta kontakt på #arena for avtale om tilgang.</li>\n</ul>\n\n<p>Feilhåndtering:</p>\n<ul>\n<li>400- og 500-feil som returneres av selve API'et vil normalt inneholde et ApiError-objekt\nmed detaljer om feilen. Se Schemas nedenfor for definisjon.</li>\n</ul>"
  version: '1.0'
servers:
  - url: https://arena-api-q2.intern.dev.nav.no
    description: Generated server url
tags:
  - name: Maalgrupper
    description: API for å hente målgrupper til personer.
  - name: Tilleggsstonader
    description: API for å hente tilleggsstønader for personer.
paths:
  /api/v1/tilleggsstoenad/aktiviteter:
      get:
        tags:
          - Tilleggsstonader
        summary: Finner aktivitetene til en person.
        operationId: getAktiviteter
        parameters:
          - name: fom
            in: query
            description: Fra-og-med dato (yyyy-MM-dd).
            required: true
            schema:
              type: string
          - name: tom
            in: query
            description: 'Til-og-med dato (yyyy-MM-dd). Default: 60 dager frem i tid.'
            required: false
            schema:
              type: string
        responses:
          '200':
            description: OK - Returnerer aktivitetene som ble funnet; en tom liste dersom ingen ble funnet.
            content:
              application/json;charset=UTF-8:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Aktivitet'
          '400':
            description: |-
              - Ugyldig eller manglende input i forespørselen.
              - Fødselsnummeret finnes ikke i Arena.
          '401':
            description: |-
              - Ugyldig eller manglende aksesstoken.
              - Applikasjonen/servicebruker er ikke preautorisert til å kalle tjenesten.
          '403':
            description: Konsumenten har ikke tilgang til ressursen.
          '500':
            description: Teknisk feil.
  /api/v1/tilleggsstoenad/dagligreise:
    get:
      tags:
        - Tilleggsstonader
      summary: Finner aktiviteter med sak, vedtak og betalingsplaner for daglige reiser til en person.
      operationId: getAktiviteterDagligreise
      parameters:
        - name: fom
          in: query
          description: Fra-og-med dato (yyyy-MM-dd).
          required: true
          schema:
            type: string
        - name: tom
          in: query
          description: 'Til-og-med dato (yyyy-MM-dd). Default: 60 dager frem i tid.'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK - Returnerer aktivitetene som ble funnet; en tom liste dersom ingen ble funnet.
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aktivitet'
        '400':
          description: |-
            - Ugyldig eller manglende input i forespørselen.
            - Fødselsnummeret finnes ikke i Arena.
        '401':
          description: |-
            - Ugyldig eller manglende aksesstoken.
            - Applikasjonen/servicebruker er ikke preautorisert til å kalle tjenesten.
        '403':
          description: Konsumenten har ikke tilgang til ressursen.
        '500':
          description: Teknisk feil.
      security:
        - BearerToken: []
  /api/v1/maalgrupper:
    get:
      tags:
        - Maalgrupper
      summary: Finner målgruppene til en person.
      operationId: getMaalgrupper
      parameters:
        - name: fom
          in: query
          description: Fra-og-med dato (yyyy-MM-dd).
          required: true
          schema:
            type: string
        - name: tom
          in: query
          description: 'Til-og-med dato (yyyy-MM-dd). Default: 2099-12-31'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK - Returnerer målgruppene som ble funnet; en tom liste dersom ingen ble funnet.
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Maalgruppe'
        '400':
          description: |-
            - Ugyldig eller manglende input i forespørselen.
            - Fødselsnummeret finnes ikke i Arena.
        '401':
          description: |-
            - Ugyldig eller manglende aksesstoken.
            - Applikasjonen/servicebruker er ikke preautorisert til å kalle tjenesten.
        '403':
          description: Konsumenten har ikke tilgang til ressursen.
        '500':
          description: Teknisk feil.
      security:
        - BearerToken: []
components:
  schemas:
    Aktivitet:
      type: object
      required:
        - aktivitetId
        - aktivitetstype
        - aktivitetsnavn
        - periode
      properties:
        aktivitetId:
          type: string
          description: Unik identifikator for aktiviteten
        aktivitetstype:
          type: string
          description: Arena-spesifikk kode for aktivitetstypen
        aktivitetsnavn:
          type: string
          description: Funksjonelt navn på aktivitet
        periode:
          $ref: '#/components/schemas/Periode'
          description: Tidsperioden som målgruppen gjelder for
        antallDagerPerUke:
          type: integer
          format: int64
          description: Aktivitetsdeltakelse i antall dager per uke
        prosentAktivitetsdeltakelse:
          type: integer
          format: int64
          description: Aktivitetsdeltakelse i prosent, relativt til 100%
        aktivitetsstatus:
          type: string
          description: Arena-spesifikk kode for aktivitetstatus
        aktivitetsstatusnavn:
          type: string
          description: Funksjonelt navn på aktivitetstatus
        erStoenadsberettigetAktivitet:
          type: boolean
          description: Flagg som spesfiserer om aktivitetstypen er stønadsberettiget
        erUtdanningsaktivitet:
          type: boolean
          description: Flagg som spesifiserer om aktivitetstype er utdanningsaktivitet
        arrangoer:
          type: string
          description: Navn på tiltaksarrangør. Vil alltid vil være en organisasjon
        saksinformasjon:
          $ref: '#/components/schemas/Saksinformasjon'
          description: Informasjon om saken
        maalgruppe:
          $ref: '#/components/schemas/Maalgruppe'
    AktivitetEndepunkt:
      type: string
      description: Type 'aktivitet' returnerer en ufiltrert aktivitetsliste for bruker mens 'dagligreise' er aktivitetsliste kun daglig reise-vedtak. Sistnevnte gir også saksinformasjon (med vedtak) for daglig reise.
      enum: [ "aktivitet", "dagligreise" ]
      example: "aktivitet"

    ApiError:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
          format: int32
        message:
          type: string
        method:
          type: string
        path:
          type: string
        correlationId:
          type: string

    Betalingsplan:
      type: object
      required:
        - betalingsplanId
        - beloep
        - utgiftsperiode
      properties:
        betalingsplanId:
          type: string
          description: Unik id til betalingsplanlinje i Arena
        beloep:
          type: integer
          format: int64
          description: Foreløpig beregnet beløp for perioden
        utgiftsperiode:
          $ref: '#/components/schemas/Periode'
          description: Periode for brukers utgift
        journalpostId:
          type: string
          description: Unik id til journalpost

    Maalgruppe:
      type: object
      required:
        - maalgruppetype
      properties:
        gyldighetsperiode:
          $ref: "#/components/schemas/Periode"
        maalgruppetype:
          $ref: "#/components/schemas/MaalgruppeType"
        maalgruppenavn:
          type: string
          description: Kort beskrivelse av målgruppen
          example: "Arbeidssøkere"

    MaalgruppeType:
      type: string
      enum: [ "ARBSOKERE", "ENSFORARBS", "ENSFORUTD", "GJENEKARBS", "GJENEKUTD", "MOTDAGPEN", "MOTTILTPEN", "NEDSARBEVN", "TIDLFAMPL", "ANNET" ]
      x-enum-varnames: [ "ARBSOKERE", "ENSFORARBS", "ENSFORUTD", "GJENEKARBS", "GJENEKUTD", "MOTDAGPEN", "MOTTILTPEN", "NEDSARBEVN", "TIDLFAMPL", "ANNET" ]

    Periode:
      type: object
      description: Tidsperiode med fom/tom
      required:
        - fom
      properties:
        fom:
          type: string
          format: date
          description: Fra dato (yyyy-MM-dd)
          example: 2020-01-01
        tom:
          type: string
          format: date
          description: Til dato (yyyy-MM-dd)
          example: 2030-01-01

    Saksinformasjon:
      type: object
      required:
        - saksnummerArena
        - sakstype
      properties:
        saksnummerArena:
          type: string
          description: Unikt saksnummer i Arena
        sakstype:
          type: string
          description: Sakstype. TSO/TSR
        vedtaksinformasjon:
          type: array
          items:
            $ref: '#/components/schemas/Vedtaksinformasjon'
          description: Liste av vedtak

    Vedtaksinformasjon:
      type: object
      required:
        - vedtakId
        - dagsats
        - periode
        - trengerParkering
      properties:
        vedtakId:
          type: string
          description: Unik id for vedtaket
        forventetDagligParkeringsutgift:
          type: integer
          format: int64
          description: Forventet daglig parkeringsutgift
        dagsats:
          type: integer
          format: int64
          description: Dagsats uten parkering
        periode:
          $ref: '#/components/schemas/Periode'
          description: Periode for aktivitetens vedtak
        trengerParkering:
          type: boolean
          description: Opplysning om bruker har krysset av for behov for parkering i søknaden. Skal brukes i logikk i innsending av påløpte utgifter
        betalingsplan:
          type: array
          items:
            $ref: '#/components/schemas/Betalingsplan'
          description: Liste av betalingsplanlinjer

  securitySchemes:
    BearerToken:
      type: http
      description: Lim inn aksesstoken utstedt av Azure AD, REST-STS eller TokenX/ID-porten. (NB! Uten "Bearer" foran.)
      scheme: bearer
      bearerFormat: JWT
