apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsending-api
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

spec:
  image: {{image}}
  port: 9064
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  leaderElection: true

  tokenx:
    enabled: true
  azure:
    application:
      enabled: true

  accessPolicy:
    inbound:
      rules:
        - application: send-inn-frontend
        - application: send-inn-frontend-alt
        - application: skjemautfylling
          namespace: skjemadigitalisering
        - application: skjemautfylling-delingslenke
          namespace: skjemadigitalisering
        - application: skjemautfylling-experimental
          namespace: skjemadigitalisering
    outbound:
      external:
      {{#each outboundExternalHosts}}
       - host: "{{this}}"
      {{/each}}
      rules:
      {{#each outboundRulesGcpApplications}}
        - application: "{{this}}"
      {{/each}}

  ingresses:
  {{#each INGRESSES}}
    - "{{this}}"
  {{/each}}

  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: {{ database-name }}
            envVarPrefix: DATABASE

  envFrom:
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"

  env:
    - name: DATABASE_NAME
      value: {{ database-name }}
    - name: SANITY_HOST
      value: {{ sanity-host }}
    - name: SANITY_ENDPOINT
      value: {{ sanity-endpoint }}
    - name: FILESTORAGE_HOST
      value: {{ filestorage-host }}
    - name: FILESTORAGE_ENDPOINT
      value: {{ filestorage-endpoint }}
    - name: FILESTORAGE_PARAMETERS
      value: {{ filestorage-parameters }}
    - name: SOKNADSMOTTAKER_HOST
      value: {{ soknadsmottaker-host }}
    - name: SOKNADSMOTTAKER_ENDPOINT
      value: {{ soknadsmottaker-endpoint }}
    - name: PUBLISERE_BRUKERNOTIFIKASJONER
      value: {{ publisere-brukernotifikasjoner }}
    - name: TJENESTE_URL
      value: {{ tjeneste-url }}
    - name: GJENOPPTA_SOKNADS_ARBEID
      value: {{ gjenoppta-soknads-arbeid }}
    - name: ETTERSENDE_PA_SOKNAD
      value: {{ ettersende-pa-soknad }}
    - name: MAX_FILE_SIZE
      value: {{ max-file-size }}
    - name: MAX_FILE_SIZE_SUM
      value: {{ max-file-size-sum }}
    - name: APP_VERSION
      value: {{ app-version }}
    - name: SPRING_PROFILES_ACTIVE
      value: {{ spring-profiles-active }}
