apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application-name}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "51M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"

spec:
  image: {{image}}
  port: 9064
  startup:
    path: /health/isReady
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  liveness:
    path: /health/isAlive
    initialDelay: 30
  readiness:
    path: /health/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 6
  resources:
    limits:
      cpu: 3000m
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 1Gi
  leaderElection: true
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka-pool}}
    streams: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{AZURE_TENANT}}
      claims:
        extra:
          - NAVident

  accessPolicy:
    inbound:
      rules:
      {{#each accessPolicyInbound.applications}}
        - application: "{{this.name}}"
          {{#if this.namespace}}
          namespace: "{{this.namespace}}"
          {{/if}}
          {{#if this.cluster}}
          cluster: "{{this.cluster}}"
          {{/if}}
          {{#if (this.roles)}}
          permissions:
            roles:
            {{#each this.roles as |role|}}
              - "{{role}}"
            {{/each}}
          {{/if}}
          {{#if (this.scopes)}}
          permissions:
            scopes:
            {{#each this.scopes as |scope|}}
              - "{{scope}}"
            {{/each}}
          {{/if}}
      {{/each}}

    outbound:
      external:
      {{#each accessPolicyOutbound.external-hosts}}
        - host: "{{this}}"
      {{/each}}
      rules:
      {{#each accessPolicyOutbound.current-namespace}}
        - application: "{{this}}"
      {{/each}}
      {{#each accessPolicyOutbound.other-namespace}}
        - application: "{{this.application}}"
          namespace: "{{this.namespace}}"
      {{/each}}

  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}

  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{ tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ default_database_size }}
        diskAutoresize: true
        autoBackupHour: 6
        databases:
          - name: {{ database-name }}
            envVarPrefix: DATABASE
    buckets:
      - name: "{{ bucket-name-file-storage }}"
        lifecycleCondition:
          age: 1

  env:
    - name: FILE_STORAGE_BUCKET_NAME
      value: "{{ bucket-name-file-storage }}"
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
