apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{application-name}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "51M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"

spec:
  image: {{image}}
  port: 9064
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 6
  resources:
    limits:
      cpu: 3000m
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 1Gi
  leaderElection: true
  kafka:
    pool: {{kafka-pool}}
    streams: true

  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: {{AZURE_TENANT}}

  accessPolicy:
    inbound:
      rules:
        - application: send-inn-frontend
        - application: send-inn-frontend-alt
        - application: soknadsarkiverer
        - application: dokumentinnsending-send-inn
        - application: skjemautfylling
          namespace: skjemadigitalisering
        - application: skjemautfylling-delingslenke
          namespace: skjemadigitalisering
        - application: skjemautfylling-experimental
          namespace: skjemadigitalisering
        - application: skjemautfylling-preprod
          namespace: skjemadigitalisering
        - application: skjemautfylling-preprod-alt
          namespace: skjemadigitalisering
        - application: fyllut-ettersending
          namespace: skjemadigitalisering
        - application: debug-dings
          namespace: plattformsikkerhet
          cluster: dev-gcp
    outbound:
      external:
      {{#each outboundExternalHosts}}
        - host: "{{this}}"
      {{/each}}
      rules:
        - application: soknadsmottaker
        - application: soknadsveiviser
          cluster: prod-gcp
          namespace: skjemadigitalisering
        - application: clamav
          namespace: nais-system

  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}

  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: {{ tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ default_database_size }}
        diskAutoresize: true
        autoBackupHour: 6
        databases:
          - name: {{ database-name }}
            envVarPrefix: DATABASE

  envFrom:
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"

  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
