apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsending-api
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

spec:
  image: {{image}}
  port: 9064
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  ingresses:
  {{#each INGRESSES as |url|}}
     - {{url}}
  {{/each}}

  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: {{ DATABASE_NAME }}
            envVarPrefix: DATABASE

  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: send-inn-frontend
        - application: skjemautfylling
          namespace: skjemadigitalisering
        - application: skjemautfylling-delingslenke
          namespace: skjemadigitalisering
        - application: skjemautfylling-experimental
          namespace: skjemadigitalisering
    outbound:
      rules:
      {{#each outboundRulesGcpApplications}}
         - application: "{{this}}"
      {{else}}
        []
      {{/each}}
      #      {{#each outboundRulesFssApplications}}
      #         - application: "{{this}}"
      #           cluster: {{fssCluster}}
      #      {{else}}
      #        []
      #      {{/each}}
      external:
      {{#each outboundExternalHosts}}
        - host: "{{this}}"
      {{else}}
        []
      {{/each}}

  envFrom:
    - secret: innsending-api-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"

  env:
    - name: APP_VERSION
      value: {{ VERSION }}
    - name: SPRING_PROFILES_ACTIVE
      value: {{ SPRING_PROFILES_ACTIVE }}
