apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: innsending-api
  namespace: team-soknad
  labels:
    team: team-soknad
  annotations:
    nais.io/read-only-file-system: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

spec:
  image: {{image}}
  port: 9064
  liveness:
    path: /health/isAlive
    initialDelay: 20
  readiness:
    path: /health/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  ingresses:
  {{#each INGRESSES}}
    - "{{this}}"
  {{/each}}

  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: {{ DATABASE_NAME }}
            envVarPrefix: DATABASE

  accessPolicy:
    inbound:
      rules:
        - application: send-inn-frontend
        - application: send-inn-frontend-alt
        - application: skjemautfylling
          namespace: skjemadigitalisering
        - application: skjemautfylling-delingslenke
          namespace: skjemadigitalisering
        - application: skjemautfylling-experimental
          namespace: skjemadigitalisering
    outbound:
      external:
      {{#each outboundExternalHosts}}
       - host: "{{this}}"
      {{else}}
        []
      {{/each}}
      rules:
      {{#each outboundRulesGcpApplications}}
        - application: "{{this}}"
      {{else}}
        []
      {{/each}}

  tokenx:
    enabled: true
  azure:
    application:
      enabled: true

  envFrom:
    - secret: shared-innsending-secret
      metadata:
        annotations:
          reloader.stakater.com/match: "true"

  env:
    - name: SANITY_HOST
      value: {{ SANITY_HOST }}
    - name: SANITY_ENDPOINT
      value: {{ SANITY_ENDPOINT }}
    - name: FILESTORAGE_HOST
      value: {{ FILESTORAGE_HOST }}
    - name: FILESTORAGE_ENDPOINT
      value: {{ FILESTORAGE_ENDPOINT }}
    - name: FILESTORAGE_PARAMETERS
      value: {{ FILESTORAGE_PARAMETERS }}
    - name: SOKNADSMOTTAKER_HOST
      value: {{ SOKNADSMOTTAKER_HOST }}
    - name: SOKNADSMOTTAKER_ENDPOINT
      value: {{ SOKNADSMOTTAKER_ENDPOINT }}
    - name: PUBLISERE_BRUKERNOTIFIKASJONER
      value: {{ PUBLISERE_BRUKERNOTIFIKASJONER }}
    - name: TJENESTE_URL
      value: {{ TJENESTE_URL }}
    - name: GJENOPPTA_SOKNADS_ARBEID
      value: {{ GJENOPPTA_SOKNADS_ARBEID }}
    - name: ETTERSENDE_PA_SOKNAD
      value: {{ ETTERSENDE_PA_SOKNAD }}
    - name: MAX_FILE_SIZE
      value: {{ MAX_FILE_SIZE }}
    - name: MAX_FILE_SIZE_SUM
      value: {{ MAX_FILE_SIZE_SUM }}
    - name: APP_VERSION
      value: {{ APP_VERSION }}
    - name: SPRING_PROFILES_ACTIVE
      value: {{ SPRING_PROFILES_ACTIVE }}
