openapi: 3.0.3
info:
  description: >
    When a user applies for a benefit (_sender inn en søknad_), one or more documents are
    sent in to NAV. This component acts as a REST-endpoint to which the systems that the user uses can send
    metadata about the benefit. The documents themselves **must** be sent to a different system,
    [Soknadsfillager](https://www.github.com/navikt/soknadsfillager), before calling Soknadsmottaker.
    When Soknadsmottaker receives data, it will be converted, serialized as an Avro message and put on a
    Kafka topic.
  version: 2.0.0
  title: Soknadsmottaker
  contact:
    name: team-soknad
    email: team-soknad@nav.no
  license:
    name: MIT License
    url: https://github.com/navikt/soknadsmottaker/blob/main/LICENSE
tags:
  - name: receive
    description: Receives benefit applications
  - name: health
    description: Application health endpoint

paths:
  /soknad:
    post:
      summary: Receives benefit application
      description: Receives a benefit application, which will lead to it being put on a Kafka topic and archived.
      operationId: receive

      parameters:
        - in: header
          name: X-dryRun
          description: >
            If set to "enabled" or if omitted, the service will only log the requests sent,
            nothing will be sent to Kafka topics. Set to "disabled" to enable proper archiving.
          example: enabled
          required: false
          schema:
            type: string

      requestBody:
        description: Metadata about the benefit application being sent in.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Soknad"
        required: true

      responses:
        200:
          description: Successful operation
      tags:
        - soknad

  /notify/new:
    post:
      summary: Message in order to publish to Kafka hosted on Aiven user notification - Beskjed or Oppgave
      description: Depending on input, a message or a task user notification with a link to continue work is to be published
      operationId: newNotification

      requestBody:
        description: Data neccessary in order to publish a new task or message user notification.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddNotification"
        required: true

      responses:
        200:
          description: Successful operation
      tags:
        - new-notification

  /notify/done:
    post:
      summary: Message in order to publish message in order to cancel an user notification
      description: After an application is sent in or deleted previous added user notification shall be canceled
      operationId: cancelNotification

      requestBody:
        description: Data neccessary to identify user notification to be closed.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SoknadRef"
        required: true

      responses:
        200:
          description: Successful operation
      tags:
        - cancel-notification


  /health/ping:
    get:
      summary: Pings the application to see if it responds
      description: Pings the application to see if it responds
      operationId: ping

      security: []   # No security
      responses:
        '200':
          description: Successful operation; application is responding
      tags:
        - health

  /health/isAlive:
    get:
      summary: Checks if the application and its dependencies up
      description: Checks if the application and its dependencies are up and running.
      operationId: isAlive

      security: []   # No security
      responses:
        '200':
          description: Successful operation; application is alive
        '500':
          description: The application or one of its dependencies are not up and running.
      tags:
        - health

  /health/isReady:
    get:
      summary: Checks if the application is ready to accept traffic
      description: Checks if the application is ready to accept traffic.
      operationId: isReady

      security: []   # No security
      responses:
        '200':
          description: Successful operation; application is ready
        '503':
          description: The application or one of its dependencies are not ready
      tags:
        - health


components:
  schemas:
    Soknad:
      type: object
      required:
        - innsendingId
        - erEttersendelse
        - personId
        - tema
        - dokumenter
      properties:
        innsendingId:
          type: string
          description: >
            Unik id for forsendelsen. Denne **må** være unik. Id brukes på flere måter;
            dels for sporing gjennom verdikjeden, dels som key på Kafka-topicen som Soknadsarkiverer leser. I tillegg
            blir id sendt inn til Joark. Id blir lagret i joark sin journalpost i kolonnen `eksternReferanseId`. Hvis id
            ikke er unik vil Joark svare med, `HttpStatus=Conflict`. Dette for å hindre at samme forsendelse arkiveres
            flere ganger.
          example: 2f9b8d25-1056-4827-8ddd-cedab7fafaaf
        erEttersendelse:
          type: boolean
          description: Markerer hvis dette er en ettersendelse til en tidligere insendt Soknad.
          example: true
        personId:
          type: string
          description: Brukerens fødselsnummer (11 siffer).
          example: 10108000398
        tema:
          type: string
          description: Temaet som forsendelsen tilhører.
          example: AAP
        dokumenter:
          type: array
          items:
            $ref: "#/components/schemas/DocumentData"
          description: Hver Soknad kan ha flere vedlegg. Denne listen beskriver metadata om disse dokumentene.

    DocumentData:
      type: object
      required:
        - skjemanummer
        - erHovedskjema
        - tittel
        - varianter
      properties:
        skjemanummer:
          type: string
          description: Skjemanummer/vedleggsnummer som dokumentet gjelder.
          example: NAV 11-12.12
        erHovedskjema:
          type: boolean
          description: >
            Markerer hvis dette er hovedskjemaet for innsendingen. Kun ett dokument kan være markert med
            `erHovedskjema = true`.
          example: true
        tittel:
          type: string
          description: Tittel på dokumentet.
          example: Søknad om tilleggsstønader
        varianter:
          type: array
          items:
            $ref: "#/components/schemas/Varianter"
          description: >
            Det kan sendes inn flere varianter av samme dokument; for eksempel kan én søknaden sendes inn med en PDF/A
            og en json variant av søknaden.
            Denne lista inneholder metadata, der hver variant representerer en fysisk fil.

    Varianter:
      type: object
      required:
        - id
        - mediaType
        - filnavn
        - filtype
      properties:
        id:
          type: string
          description: Unikt id på fila. En fil med dette id må ha blitt sendt til Soknadsfillager.
          example: 18777177-eba3-4f58-b9b9-694e7171a030
        mediaType:
          type: string
          description: Hva for [Media type](https://en.wikipedia.org/wiki/Media_type) fila har.
          example: application/pdf
        filnavn:
          type: string
          description: Navn for systemdefinerte filer, eller navn spesifisert av bruker.
          example: tilleggsstonader.xml
        filtype:
          type: string
          description: Metadata about attached documents
          example: XML

    AddNotification:
      type: object
      required:
        - soknadRef
        - brukernotifikasjonInfo
      properties:
        soknadRef:
          $ref: "#/components/schemas/SoknadRef"
        brukernotifikasjonInfo:
          $ref: "#/components/schemas/NotificationInfo"

    SoknadRef:
      type: object
      required:
        - innsendingId
        - erEttersendelse
        - groupId
        - personId
        - tidpunktEndret
      properties:
        innsendingId:
          type: string
          description: >
            Unik id for forsendelsen. Denne **må** være unik. Id brukes på flere måter;
            dels for sporing gjennom verdikjeden, dels som key på Kafka-topicen som Soknadsarkiverer leser. I tillegg
            blir id sendt inn til Joark. Id blir lagret i joark sin journalpost i kolonnen `eksternReferanseId`. Hvis id
            ikke er unik vil Joark svare med, `HttpStatus=Conflict`. Dette for å hindre at samme forsendelse arkiveres
            flere ganger.
          example: 92ee15dd-dc49-4c95-b9b6-6224bae088a0
        erEttersendelse:
          type: boolean
          description: Markerer hvis dette er en ettersendelse til en tidligere insendt Soknad.
          example: true
        groupId:
          type: string
          description: Id for gruppering av notifikasjoner som "hører" sammen, f.eks. søknad med etterfølgende ettersendelser.
          example: 2f9b8d25-1056-4827-8ddd-cedab7fafaaf
        personId:
          type: string
          description: Brukerens fødselsnummer (11 siffer).
          example: 10108000398
        tidpunktEndret:
          type: string
          format: date-time
          description: Tidpunkt når forsendelsen sist endrets, i UTC.
          example: 2022-04-06T14:10:00Z

    NotificationInfo:
      type: object
      required:
        - notifikasjonsTittel
        - lenke
        - antallAktiveDager
        - eksternVarsling
      properties:
        notifikasjonsTittel:
          type: string
          description:
            Tittel tekst på Brukernotifikasjon.
          example:
            Du har påbegynt en søknad om Fremmøteskjema ved deltakelse på kurs
        lenke:
          type: string
          description:
            Lenke for å åpne søknad/ettersendingssøknad eller starte ettersending fra Brukernotifikasjon.
          example:
            https://tjenester.nav.no/soknaddagpenger-innsending/soknad/10014Qi1G,
            https://tjenester.nav.no/soknadinnsending/soknad/10014Qi1G eller
            https://tjenester-q1.nav.no/dokumentinnsending/oversikt/10014Qi1G
        antallAktiveDager:
          type: integer
          description:
            Antall dager Brukernotifikasjonen skal vises.
          example: 56
        eksternVarsling:
          type: array
          description: Angir om varsel skal sendes til søker på f.eks. SMS eller epost.
          items:
            $ref: "#/components/schemas/Varsel"

    Varsel:
      type: object
      required:
        - kanal
        - tekst
      properties:
        kanal:
          type: string
          description: Angir på hvilken kanal varsel skal sendes til søker.
          example: epost
          enum:
            - sms
            - epost
        tekst:
          type: string
          description: Spesifiserer en overordnet beskrivelse av et varsel til søker.
          example: Ny soknad opprettet. Logg inn på NAV for å finne lenke for å åpne denne.
        tittel:
          type: string
          nullable: true
          description: Spesifiserer en tittel på epost dersom det sendes varsel via epost.
          example: Notifikasjon fra NAV

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

security:
  - basicAuth: []

externalDocs:
  description: Documentation of the whole archiving system
  url: https://github.com/navikt/archiving-infrastructure/wiki
