server:
  port: 9064
  max-http-header-size: 16384

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, refresh, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true

cron:
  startSlettGamleIkkeInnsendteSoknader: 0 0 2 * * *
  slettEldreEnn: 56
  startSlettInnsendteFiler: 0 0 5 * * *
  slettInnsendtFilEldreEnn: 1
  startSlettPermanentIkkeInnsendteSoknader: 0 0 3 * * *
  slettPermanentEldreEnn: 365
  # Kjører hvert 11. minutt
  runVerifyArchivedApplications: 0 0,11 0 ? * *

ettersendingsfrist: 14

verifyArchivedApplications:
  offsetMinutes: 95

kafka:
  applicationId: ${KAFKA_STREAMS_APPLICATION_ID}
  brokers: ${KAFKA_BROKERS}
  security:
    enabled: ${KAFKA_SECURITY}
    protocol: SSL
    keyStoreType: PKCS12
    keyStorePath: ${KAFKA_KEYSTORE_PATH}
    keyStorePassword: ${KAFKA_CREDSTORE_PASSWORD}
    trustStorePath: ${KAFKA_TRUSTSTORE_PATH}
    trustStorePassword: ${KAFKA_CREDSTORE_PASSWORD}
  topics:
    messageTopic: ${KAFKA_MESSAGE_TOPIC}

