server:
  port: 9064

management:
  endpoint:
    health:
      show-details: always
  endpoints.web:
    exposure:
      include: info, health, metrics, refresh, prometheus
    base-path: "/internal"
  metrics:
    export:
      prometheus:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: test | default | spring

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres

restconfig:
  version: 1.0
  username: srvuser
  password: password
  sharedUsername: innsending
  sharedPassword: password
  maxFileSize: 104857600
  sanityHost: https://www.nav.no
  sanityEndpoint: /soknader/api/sanity/skjemautlisting
  filestorageHost: http://localhost:9042
  filestorageEndpoint: /filer
  filestorageParameters: /
  filesInOneRequestToFilestorage: 10
  soknadsMottakerHost: http://localhost:9043
  soknadsMottakerEndpoint: /save
  frontEndFortsettEndpoint: http://localhost:3000/dokumentinnsending/oversikt/
  pdlUrl: http://pdf-api.pdl

brukernotifikasjonconfig:
  profiles: test
  tjenesteUrl: https://localhost
  gjenopptaSoknadsArbeid: /dokumentinnsending/oversikt/
  ettersendePaSoknad: /dokumentinnsending/ettersending/
  publisereEndringer: true

no.nav.security.jwt:
  mock:
    enable: true
  issuers:
    issuer_name: tokendingsTest
    discoveryurl: http://metadata
    accepted_audience: aud-localhost

---
spring:
  config:
    activate:
      on-profile: dev | prod | docker

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}MB
      max-request-size: ${MAX_FILE_SIZE}MB

  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 10001
      max-lifetime: 30001
      leak-detection-threshold: 30000

restconfig:
  version: ${APP_VERSION}
  username: ${APPLICATION_USERNAME}
  password: ${APPLICATION_PASSWORD}
  sharedUsername: ${SHARED_USERNAME}
  sharedPassword: ${SHARED_PASSWORD}
  maxFileSize: ${MAX_FILE_SIZE}
  sanityHost: ${SANITY_HOST}
  sanityEndpoint: ${SANITY_ENDPOINT}
  filestorageHost: ${FILESTORAGE_HOST}
  filestorageEndpoint: ${FILESTORAGE_ENDPOINT}
  filestorageParameters: ${FILESTORAGE_PARAMETERS}
  filesInOneRequestToFilestorage: 10
  soknadsMottakerHost: ${SOKNADSMOTTAKER_HOST}
  soknadsMottakerEndpoint: ${SOKNADSMOTTAKER_ENDPOINT}
  frontEndFortsettEndpoint: https://${TJENESTE_URL}${GJENOPPTA_SOKNADS_ARBEID}
  pdlUrl: http://pdf-api.pdl


brukernotifikasjonconfig:
  profiles: ${SPRING_PROFILES_ACTIVE}
  tjenesteUrl: ${TJENESTE_URL}
  gjenopptaSoknadsArbeid: ${GJENOPPTA_SOKNADS_ARBEID}
  ettersendePaSoknad: ${ETTERSENDE_PA_SOKNAD}
  publisereEndringer: ${PUBLISERE_BRUKERNOTIFIKASJONER}

no.nav.security.jwt:
  issuer.tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: ${TOKEN_X_CLIENT_ID}

