name: Merge Schedule
permissions:
  contents: write
  pull-requests: write
  id-token: write
  statuses: write
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # https://crontab.guru/every-hour
    - cron: '0 * * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          time_zone: 'UTC'
          merge_method: merge
          require_statuses_success: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.SCHEDULE_MERGE_PAT }}
