name: Install and test
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.github/workflows/**.yml'

permissions:
  packages: "read"
  id-token: "write" # for nais/login

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Oslo"
      - name: NAIS login
        uses: nais/login@v0
        id: image-registry
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: team-soknad
      - run: gcloud auth configure-docker ${{ steps.image-registry.outputs.registry }}
      - name: Maven clean install
        run: mvn clean install
