name: Install and test
on:
  pull_request:
        paths-ignore:
          - '**.md'
          - '**/**.md'
          - '.github/workflows/**.yml'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Oslo"
      - name: Maven clean install
        run: mvn clean install


