name: Install and test
on: push

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17.x'
          cache: 'maven'
      - name: Maven clean install
        run: mvn clean install


