name: Install and test
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**/**.md'
      - '.github/workflows/**.yml'
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
      - '**/**.md'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Oslo"

      - name: Maven build
        env:
          GITHUB_NAV_TOKEN: ${{ secrets.READER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: |
          mvn clean install --settings maven-settings.xml
